---
title: Testing Multivariate simulation for decreasing response variance
author: Raju Rimal
runtime: shiny
output: 
  html_document:
    theme: cosmo
---

# Simulation Parameters

```{r, include = FALSE}
knitr::opts_chunk$set(
  comment = NULL,
  echo = FALSE
)
library(shiny)
library(simrel)
library(gridExtra)
```

```{r}
fluidRow(
  column(3, numericInput("n", "Number of observation", 100, min = 10, width = "100%")),
  column(3, numericInput("p", "Number of predictors", 10, min = 2, width = "100%")),
  column(3, numericInput("m", "Number of responses", 3, min = 2, width = "100%")),
  column(2, numericInput("seed", "seed", 123, min = 2, width = "100%")),
  column(1, actionButton('simulate', label = NULL, class="btn-primary", icon = icon("refresh"), width = '100%')),
  column(4, textInput("q", "Number of relevant predictors", value = "5, 4", width = "100%")),
  column(4, textInput("relpos", "Position of Relevant components", value = "1, 2; 3, 4, 6", width = '100%')),
  column(4, textInput("ypos", "Position of response components", value = "1; 2, 3", width = '100%')),
  column(4, sliderInput("gamma", "Decay factor of eigenvector of predictors", 
                        value = 0.5, min = 0, max = 3, width = '100%', step = 0.01)),
  column(4, sliderInput("eta", "Decay factor of eigenvector of response", 
                        value = 0.5, min = 0, max = 3, width = '100%', step = 0.01)),
  column(4, textInput("R2", "Coefficient of Determination", value = "0.7, 0.8", width = '100%'))
)

evl <- function(x) {
  out <- lapply(strsplit(unlist(strsplit(x, ";")), ","), as.numeric)
  if (length(out) == 1) out <- out[[1]]
  return(out)
}

opts <- reactive({
  list(
    n = input$n,
    p = input$p,
    q = evl(input$q),
    relpos = evl(input$relpos),
    gamma = input$gamma,
    R2 = evl(input$R2),
    ypos = evl(input$ypos),
    m = input$m,
    eta = input$eta,
    type = "multivariate"
  )
})
```

## Simulation and Modeling
### Covariance of Response

```{r}
sobj <- eventReactive(input$simulate, {
  set.seed(input$seed)
  do.call(simrel, opts())
})

column(
  width = 6, 
  h4("Estimated covariance of response"),
  div("Covariance of simulated response"),
  div(code("cov(sim.obj[['Y']]")),
  renderPrint({
    round(var(sobj()$Y), 4)
  })
)

column(
  width = 6, 
  h4("True covariance of response"),
  div("Covariance of response extracted from true sigma matrix"),
  div(code("cov(sim.obj[['Sigma']][1:m, 1:m])")),
  renderPrint({
    sigma <- sobj()$Sigma
    m <- sobj()$m
    round(sigma[1:m, 1:m], 4)
  })
)
```

### Coefficient of Determination
```{r}
mdl <- reactive({
  dta <- data.frame(
    y = I(sobj()[["Y"]]),
    x = I(sobj()[["X"]])
  )
  return(lm(y ~ x, data = dta))
})
column(
  width = 6,
  h4("Estimated coefficient of determination"),
  div("\\(R^2\\) obtained from", code("lm")),
  renderPrint({
    sapply(summary(mdl()), function(x) {
      round(unname(x[["r.squared"]]), 3)
    })
  }),
  h4("Correlation between true and fitted response"),
  div("\\[\\text{cor}(Y, \\widehat{Y})\\]"),
  column(
    12,
    renderPrint({
      cor(sobj()[["Y"]], fitted(mdl()))
    })
  )
)
column(
  width = 6,
  h4("True coefficient of determination"),
  div(
    column(
      width = 12, 
      h5("\\[\\rho_y^2 = \\Sigma_{xy}^t\\Sigma_{xx}^{-1}\\Sigma_{xy}\\left[\\text{diag(diag(}\\Sigma_{yy}\\text{))}\\right]^{-1}\\]"),
      renderPrint({
        sobj()[["RsqYalt"]]
      })
    ),
    column(
      width = 12,
      h5("Rsq matrix for Y"),
      div("\\[\\rho^2_y = Q\\cdot \\rho^2_w\\cdot Q^t = Q \\cdot \\Sigma_{zw}^t\\Sigma_{zz}^{-1}\\Sigma_{zw}\\Sigma_{ww}^{-1} \\cdot Q^t\\]"),
      renderPrint({
        sobj()[["RsqY"]]
      })
    ),
    column(
      width = 12,
      h5("Theoritical Correlation between fitted and true response"),
      div("\\[\\Sigma_{y|x}\\]"),
      renderPrint({
        m <- sobj()[["m"]]
        sigma0 <- sobj()[["SigmaWZ"]]
        rotY <- sobj()[["Yrotation"]]
        rho_w <- sigma0[c(1:m), -c(1:m)] %*% 
          solve(sigma0[-c(1:m), -c(1:m)]) %*%
          sigma0[-c(1:m), c(1:m)] %*%
          solve(sigma0[1:m, 1:m])
        rho_w
      }),
      h5("Minimum Error"),
      div("\\[Q\\cdot (\\Sigma_{ww} - \\Sigma_{zw}^t\\Sigma_{zz}^{-1}\\Sigma_{zw}\\Sigma_{ww}^{-1}) \\cdot Q^t\\]"),
      renderPrint({
        sobj()[["minerror"]]
      })
    )
  ))
```

<!-- # Covariance Plot -->
```{r, fig.asp = 0.9, eval = FALSE}
fluidRow(
  column(
    12, 
    renderPlot({
      p1 <- cov_plot(sobj(), type = "relpos")
      p2 <- cov_plot(sobj(), type = "rotation")
      p3 <- cov_plot(sobj(), type = "relpred")
      gridExtra::grid.arrange(p1, p2, p3, ncol = 3)
    }, res = 100)
  )
)
```

