#' @title  Plotting Functions
#' @name plot_beta
#' @param obj A simrel object
#' @param base_theme Base ggplot theme to apply
#' @param lab_list List of labs arguments such as x, y, title, subtitle
#' @param theme_list List of theme arguments to apply in the plot
#' @return A plot of true regression coefficients for the simulated data
#' @import ggplot2
#' @examples
#' sobj <- multisimrel()
#' sobj %>% 
#'     plot_beta(
#'         base_theme = ggplot2::theme_bw,
#'         lab_list = list(
#'             title = "Regression Coefficients",
#'             subtitle = "From Simulation",
#'             y = "True Regression Coefficients"
#'         ),
#'         theme_list = list(
#'             legend.position = "bottom"
#'         )
#'     )
#' @rdname plot_beta
#' @export
plot_beta <- function(obj, base_theme = theme_grey, lab_list = NULL, theme_list = NULL) {
  beta_df <- obj %>% tidy_beta()
  plt <- beta_df %>% 
    modify_at("Response", as.factor) %>% 
    ggplot(aes_string("Predictor", "BetaCoef",
               color = "Response",
               group = "Response")) +
    geom_hline(yintercept = 0,
               color = "grey2",
               linetype = 2) +
    geom_line() +
    geom_point() +
    base_theme()
  if (!is.null(lab_list)) {
    plt  <- plt + do.call(labs, lab_list)
  }
  if (!is.null(theme_list)) {
    plt <- plt + do.call(theme, theme_list)
  }
  return(plt)
}

#' @name plot_covariance
#' @title Plot Covariance between predictor (components) and response (components)
#' @param sigma_df A data.frame generated by tidy_sigma
#' @param lambda_df A data.frame generated by tidy_lambda
#' @param base_theme Base ggplot theme to apply
#' @param lab_list List of labs arguments such as x, y, title, subtitle
#' @param theme_list List of theme arguments to apply in the plot
#' @return A plot of true regression coefficients for the simulated data
#' @import ggplot2
#' @examples
#' sobj <- bisimrel(p = 12)
#' sigma_df <- sobj %>% 
#'     cov_mat(which = "zy") %>% 
#'     tidy_sigma() %>% 
#'     abs_sigma()
#' lambda_df <- sobj %>% 
#'     tidy_lambda()
#' plot_covariance(
#'     sigma_df,
#'     lambda_df,
#'     base_theme = ggplot2::theme_bw,
#'     lab_list = list(
#'         title = "Covariance between Response and Predictor Components",
#'         subtitle = "The bar represents the eigenvalues predictor covariance",
#'         y = "Absolute covariance",
#'         x = "Predictor Component",
#'         color = "Response Component"
#'     ),
#'     theme_list = list(
#'         legend.position = "bottom"
#'     )
#' )
#' @rdname plot_covariance
#' @export
#' 
plot_covariance <- function(sigma_df, lambda_df, base_theme = theme_grey, lab_list = NULL, theme_list = NULL) {
  pjtr <- position_dodge(0.5)
  plt <- sigma_df %>% 
    modify_at("Response", as.factor) %>% 
    ggplot(aes_string(
      x = 'Predictor',
      y = 'Covariance',
      color = 'Response',
      group = 'Response'
    )) +
    geom_bar(
      data = lambda_df,
      aes_string(x = 'Predictor', y = 'lambda'),
      inherit.aes = FALSE,
      fill = "lightgrey",
      stat = "identity"
    ) +
    geom_hline(yintercept = 0, color = "grey", linetype = "dashed") +
    geom_line(position = pjtr) +
    geom_point(position = pjtr) +
    base_theme()
  if (!is.null(lab_list)) {
    plt  <- plt + do.call(labs, lab_list)
  }
  if (!is.null(theme_list)) {
    plt <- plt + do.call(theme, theme_list)
  }
  return(plt)
}
